requires = ["tox>=4"]
env_list = ["lint", "3.12"]
# we cannot run the latest version
# prolly because some dependencies update slowly

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
]
commands = [["python", "test/test.py"]]

[env.lint]
description = "run linters and code formatters"
skip_install = true
deps = ["ruff"]
commands = [
    ["ruff", "check", "."],
    ["ruff", "format", "--check", "."]
]
